# Generated by Django 2.1.5 on 2020-02-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200218_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='logo',
        ),
    ]
